---
leofs_module:   leo_manager_0

leo_manager_console_cui_port:           10010
leo_manager_console_json_port:          10020
leo_manager_console_cui_acceptors:      3
leo_manager_console_json_acceptors:     16
leo_manager_console_hist_display_num:   200

leofs_system_dc_id:         "dc_1"
leofs_system_cluster_id:    "leofs_1"

leofs_num_of_replica:   2
leofs_write_quorum:     1
leofs_read_quorum:      1
leofs_delete_quorum:    1
leofs_rack_rep:         0

leofs_rpc_server_acceptors:         16
leofs_rpc_server_port:              13075
leofs_rpc_server_timeout:           5000
leofs_rpc_server_conn_pool:         16
leofs_rpc_server_conn_buffer_size:  16

leofs_mdc_rep_max_target:       2
leofs_mdc_rep_num_rep_each_dc:  1

leofs_snmp_agent:   "./snmp/snmpa_manager_0/LEO-MANAGER"
leofs_snmp_conf:    "./snmp/snmpa_manager_0/leo_manager_snmp"
